/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.madhouse.dsp.Utils;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class User1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2427638438371690985L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User1\",\"namespace\":\"com.madhouse.dsp.Utils\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"favorite_number\",\"type\":[\"int\",\"null\"]},{\"name\":\"favorite_color\",\"type\":[\"string\",\"null\"]},{\"name\":\"score\",\"type\":[\"int\",\"null\"],\"default\":60}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<User1> ENCODER =
          new BinaryMessageEncoder<User1>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<User1> DECODER =
          new BinaryMessageDecoder<User1>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<User1> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<User1> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<User1>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this User1 to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a User1 from a ByteBuffer. */
  public static User1 fromByteBuffer(
          java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.Integer favorite_number;
  @Deprecated public java.lang.CharSequence favorite_color;
  @Deprecated public java.lang.Integer score;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public User1() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param favorite_number The new value for favorite_number
   * @param favorite_color The new value for favorite_color
   * @param score The new value for score
   */
  public User1(java.lang.CharSequence name, java.lang.Integer favorite_number, java.lang.CharSequence favorite_color, java.lang.Integer score) {
    this.name = name;
    this.favorite_number = favorite_number;
    this.favorite_color = favorite_color;
    this.score = score;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0: return name;
      case 1: return favorite_number;
      case 2: return favorite_color;
      case 3: return score;
      default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0: name = (java.lang.CharSequence)value$; break;
      case 1: favorite_number = (java.lang.Integer)value$; break;
      case 2: favorite_color = (java.lang.CharSequence)value$; break;
      case 3: score = (java.lang.Integer)value$; break;
      default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'favorite_number' field.
   * @return The value of the 'favorite_number' field.
   */
  public java.lang.Integer getFavoriteNumber() {
    return favorite_number;
  }

  /**
   * Sets the value of the 'favorite_number' field.
   * @param value the value to set.
   */
  public void setFavoriteNumber(java.lang.Integer value) {
    this.favorite_number = value;
  }

  /**
   * Gets the value of the 'favorite_color' field.
   * @return The value of the 'favorite_color' field.
   */
  public java.lang.CharSequence getFavoriteColor() {
    return favorite_color;
  }

  /**
   * Sets the value of the 'favorite_color' field.
   * @param value the value to set.
   */
  public void setFavoriteColor(java.lang.CharSequence value) {
    this.favorite_color = value;
  }

  /**
   * Gets the value of the 'score' field.
   * @return The value of the 'score' field.
   */
  public java.lang.Integer getScore() {
    return score;
  }

  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(java.lang.Integer value) {
    this.score = value;
  }

  /**
   * Creates a new User1 RecordBuilder.
   * @return A new User1 RecordBuilder
   */
  public static com.madhouse.dsp.Utils.User1.Builder newBuilder() {
    return new com.madhouse.dsp.Utils.User1.Builder();
  }

  /**
   * Creates a new User1 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new User1 RecordBuilder
   */
  public static com.madhouse.dsp.Utils.User1.Builder newBuilder(com.madhouse.dsp.Utils.User1.Builder other) {
    return new com.madhouse.dsp.Utils.User1.Builder(other);
  }

  /**
   * Creates a new User1 RecordBuilder by copying an existing User1 instance.
   * @param other The existing instance to copy.
   * @return A new User1 RecordBuilder
   */
  public static com.madhouse.dsp.Utils.User1.Builder newBuilder(com.madhouse.dsp.Utils.User1 other) {
    return new com.madhouse.dsp.Utils.User1.Builder(other);
  }

  /**
   * RecordBuilder for User1 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User1>
          implements org.apache.avro.data.RecordBuilder<User1> {

    private java.lang.CharSequence name;
    private java.lang.Integer favorite_number;
    private java.lang.CharSequence favorite_color;
    private java.lang.Integer score;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.madhouse.dsp.Utils.User1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[1].schema(), other.favorite_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.favorite_color)) {
        this.favorite_color = data().deepCopy(fields()[2].schema(), other.favorite_color);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.score)) {
        this.score = data().deepCopy(fields()[3].schema(), other.score);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing User1 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.madhouse.dsp.Utils.User1 other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[1].schema(), other.favorite_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.favorite_color)) {
        this.favorite_color = data().deepCopy(fields()[2].schema(), other.favorite_color);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.score)) {
        this.score = data().deepCopy(fields()[3].schema(), other.score);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Gets the value of the 'name' field.
     * @return The value.
     */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
     * Sets the value of the 'name' field.
     * @param value The value of 'name'.
     * @return This builder.
     */
    public com.madhouse.dsp.Utils.User1.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'name' field has been set.
     * @return True if the 'name' field has been set, false otherwise.
     */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'name' field.
     * @return This builder.
     */
    public com.madhouse.dsp.Utils.User1.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'favorite_number' field.
     * @return The value.
     */
    public java.lang.Integer getFavoriteNumber() {
      return favorite_number;
    }

    /**
     * Sets the value of the 'favorite_number' field.
     * @param value The value of 'favorite_number'.
     * @return This builder.
     */
    public com.madhouse.dsp.Utils.User1.Builder setFavoriteNumber(java.lang.Integer value) {
      validate(fields()[1], value);
      this.favorite_number = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'favorite_number' field has been set.
     * @return True if the 'favorite_number' field has been set, false otherwise.
     */
    public boolean hasFavoriteNumber() {
      return fieldSetFlags()[1];
    }


    /**
     * Clears the value of the 'favorite_number' field.
     * @return This builder.
     */
    public com.madhouse.dsp.Utils.User1.Builder clearFavoriteNumber() {
      favorite_number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'favorite_color' field.
     * @return The value.
     */
    public java.lang.CharSequence getFavoriteColor() {
      return favorite_color;
    }

    /**
     * Sets the value of the 'favorite_color' field.
     * @param value The value of 'favorite_color'.
     * @return This builder.
     */
    public com.madhouse.dsp.Utils.User1.Builder setFavoriteColor(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.favorite_color = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'favorite_color' field has been set.
     * @return True if the 'favorite_color' field has been set, false otherwise.
     */
    public boolean hasFavoriteColor() {
      return fieldSetFlags()[2];
    }


    /**
     * Clears the value of the 'favorite_color' field.
     * @return This builder.
     */
    public com.madhouse.dsp.Utils.User1.Builder clearFavoriteColor() {
      favorite_color = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'score' field.
     * @return The value.
     */
    public java.lang.Integer getScore() {
      return score;
    }

    /**
     * Sets the value of the 'score' field.
     * @param value The value of 'score'.
     * @return This builder.
     */
    public com.madhouse.dsp.Utils.User1.Builder setScore(java.lang.Integer value) {
      validate(fields()[3], value);
      this.score = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'score' field has been set.
     * @return True if the 'score' field has been set, false otherwise.
     */
    public boolean hasScore() {
      return fieldSetFlags()[3];
    }


    /**
     * Clears the value of the 'score' field.
     * @return This builder.
     */
    public com.madhouse.dsp.Utils.User1.Builder clearScore() {
      score = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public User1 build() {
      try {
        User1 record = new User1();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.favorite_number = fieldSetFlags()[1] ? this.favorite_number : (java.lang.Integer) defaultValue(fields()[1]);
        record.favorite_color = fieldSetFlags()[2] ? this.favorite_color : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.score = fieldSetFlags()[3] ? this.score : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<User1>
          WRITER$ = (org.apache.avro.io.DatumWriter<User1>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
          throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<User1>
          READER$ = (org.apache.avro.io.DatumReader<User1>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
          throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}